export enum VariableType {
  Float = "float64",
  Float2 = "vector2.Vector[float64]",
  Float3 = "vector3.Vector[float64]",
  Float4 = "vector4.Vector[float64]",
  FloatArray = "[]float64",
  Float2Array = "[]vector2.Vector[float64]",
  Float3Array = "[]vector3.Vector[float64]",
  Int = "int",
  Int2 = "vector2.Vector[int]",
  Int3 = "vector3.Vector[int]",
  IntArray = "[]int",
  Int2Array = "[]vector2.Vector[int]",
  Int3Array = "[]vector3.Vector[int]",
  String = "string",
  StringArray = "[]string",
  Color = "coloring.Color",
  ColorArray = "[]coloring.Color",
  ColorGradient = "coloring.Gradient[github.com/EliCDavis/polyform/drawing/coloring.Color]",
  Bool = "bool",
  AABB = "geometry.AABB",
  Quaternion = "quaternion.Quaternion",
  TRS = "trs.TRS",
  TRSArray = "[]trs.TRS",
  Image = "image.Image",
  File = "file",
}

export const VARIABLE_TYPE_OPTIONS: Array<{ value: VariableType; label: string }> = [
  { value: VariableType.Float, label: "Float" },
  { value: VariableType.Float2, label: "Float2" },
  { value: VariableType.Float3, label: "Float3" },
  { value: VariableType.Float4, label: "Float4" },
  { value: VariableType.Int, label: "Int" },
  { value: VariableType.Int2, label: "Int2" },
  { value: VariableType.Int3, label: "Int3" },
  { value: VariableType.String, label: "String" },
  { value: VariableType.Bool, label: "Bool" },
  { value: VariableType.AABB, label: "AABB" },
  { value: VariableType.Quaternion, label: "Rotation" },
  { value: VariableType.TRS, label: "Transform" },
  { value: VariableType.TRSArray, label: "Transform Array" },
  { value: VariableType.Color, label: "Color" },
  { value: VariableType.ColorArray, label: "Color Array" },
  { value: VariableType.ColorGradient, label: "Color Gradient" },
  { value: VariableType.FloatArray, label: "Float Array" },
  { value: VariableType.Float2Array, label: "Float2 Array" },
  { value: VariableType.Float3Array, label: "Float3 Array" },
  { value: VariableType.IntArray, label: "Int Array" },
  { value: VariableType.Int2Array, label: "Int2 Array" },
  { value: VariableType.Int3Array, label: "Int3 Array" },
  { value: VariableType.StringArray, label: "String Array" },
  { value: VariableType.Image, label: "Image" },
  { value: VariableType.File, label: "File" },
];
