name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows manual triggering
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main

  commands:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build Nix-cached Release Artifacts
        run: |
          nix run .#sri-check-up --print-build-logs
          nix build .#release --print-build-logs --out-link ./artifacts

  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build Nix-cached Pages Artifacts
        run: |
          nix run .#sri-check-up --print-build-logs
          nix build .#pages --print-build-logs --out-link ./dist
