on:
    push:
      paths:
        - CITATION.cff
    workflow_dispatch:
  
name: CITATION.cff
jobs:
  Validate-CITATION-cff:

    # R isn't pre-installed anymore. This should be removed once this issue is
    # resolved:
    # https://github.com/dieghernan/cff-validator/issues/16
    runs-on: ubuntu-22.04
    
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate CITATION.cff
      uses: dieghernan/cff-validator@v3